# Generated by Django 3.0.6 on 2020-06-05 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20200602_2242'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='alert',
            field=models.IntegerField(default=0),
        ),
    ]
