# Generated by Django 3.0.6 on 2020-05-30 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='title',
            new_name='board_name',
        ),
    ]
