# Generated by Django 3.0.6 on 2020-06-18 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='important',
            field=models.IntegerField(default=1),
        ),
    ]
