# Generated by Django 3.0.6 on 2020-06-02 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_auto_20200530_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='board_name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
