# Generated by Django 3.0.6 on 2020-06-18 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_category_important'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['important']},
        ),
        migrations.AlterField(
            model_name='category',
            name='important',
            field=models.PositiveIntegerField(),
        ),
    ]
