# Generated by Django 3.0.6 on 2020-06-18 06:43

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0004_auto_20200618_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='color',
            field=colorfield.fields.ColorField(default='#ffffff', max_length=18),
        ),
    ]
