# Generated by Django 3.0.6 on 2020-06-14 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('usingform', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentalertcontent',
            name='profile_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Profile'),
        ),
    ]
