# Generated by Django 3.0.6 on 2020-06-14 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usingform', '0002_auto_20200614_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentalertcontent',
            name='content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usingform.Comment'),
        ),
    ]
