# Generated by Django 3.0.6 on 2020-05-30 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usingform', '0002_auto_20200530_1758'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='defaultform',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
