# Generated by Django 3.0.6 on 2020-05-30 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_auto_20200530_1807'),
        ('usingform', '0003_auto_20200530_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='defaultform',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='category.Category'),
            preserve_default=False,
        ),
    ]
