# Generated by Django 3.0.6 on 2020-07-28 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usingform', '0004_important_board'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=140, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='defaultform',
            name='tag_set',
            field=models.ManyToManyField(blank=True, to='usingform.Tag'),
        ),
    ]
