# Generated by Django 3.0.6 on 2020-06-02 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usingform', '0004_defaultform_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='defaultform',
            options={'ordering': ['-id']},
        ),
    ]
