# Generated by Django 3.0.6 on 2020-06-04 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usingform', '0010_auto_20200604_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='files',
            field=models.FileField(blank=True, null=True, upload_to='board_file/'),
        ),
    ]
