# Generated by Django 3.0.6 on 2020-06-04 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usingform', '0012_comment_commentlike'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='main_post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='usingform.Defaultform'),
            preserve_default=False,
        ),
    ]
