# Generated by Django 3.0.6 on 2020-06-05 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_commentalert'),
        ('usingform', '0015_commentalertcontent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commentalertcontent',
            options={'ordering': ['-id']},
        ),
        migrations.CreateModel(
            name='Donotalert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usingform.Defaultform')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Profile')),
            ],
        ),
    ]
