# Generated by Django 3.0.6 on 2020-06-05 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usingform', '0016_auto_20200605_2134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentalertcontent',
            name='profile',
        ),
        migrations.AddField(
            model_name='commentalertcontent',
            name='profile_name',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
